### ISSUE TITLE
Size GIF

### ISSUE THREAD

**Issue by shahinesi** [SirTony/Gifed#1]
Hello
Thank you for your good library.
one question!
I want all the photos that are used to build GIF a size they do not know how!
For example, a small photos and a large photo thumbnail I want to be overweight or generally all the photos of my size.
GIF size can be adjusted as desired?
Tnx

**Comment by shahinesi** [comment]
![1021](https://cloud.githubusercontent.com/assets/16535600/25556738/56c8e5d2-2d17-11e7-9486-967e76668697.gif)

**Comment by clarajk** [comment]
You can resize all the images to be the same size before adding them to the gif.

```csharp
Image Resize( Image img, Size newSize )
{
    var bmp = new Bitmap( newSize.Width, newSize.Height, img.PixelFormat );
    using( var graphics = Graphics.FromImage( bmp ) )
    {
        graphics.InterpolationMode = InterpolationMode.HighQualityBicubic;
        var rect = new Rectangle( Point.Empty, newSize );
        graphics.DrawImage( img, rect );
    }

    return bmp;
}

var images = new DirectoryInfo( "C:\\images" ).EnumerateFiles().Select( fi => Image.FromFile( fi.FullName ) );
var size = new Size( 300, 300 );
var gif = new AnimatedGif();

foreach( var img in images )
{
    var newImg = img.Size != size ? Resize( img, size ) : img;
    gif.AddFrame( newImg, 5 );
}
```
